image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-browser
tasks:
  - command: mv /home/gitpod/.sdkman/candidates/java/current/bin/java /home/gitpod/.sdkman/candidates/java/current/bin/java_old; code-server --disable-telemetry --folder=/workspace/Gitpod-LineageOS-Build/lineage
  - command: cd /workspace/Gitpod-LineageOS-Build/lineage