image:
  file: .gitpod.Dockerfile
ports:
  - port: 443
    onOpen: open-browser
  - port: 8080
    onOpen: open-browser
tasks:
  - command: code-server
  - command: cd /workspace/Gitpod-LineageOS-Build/lineage; echo url="https://www.duckdns.org/update?domains=gitpod&token=b4d96824-e96c-459a-91e4-de226a8d6ff7&ip=" | curl -k -o ~/duck.log -K -